### PR TITLE
DevOps: Fix the continuous-deployment workflow

### PR DESCRIPTION
**Pull request by sphuber**
The workflow was broken as the `check_version.py` file was expecting the tag as the last argument to its invocation, but was really receiving the ``github.ref`` environment variable which includes the `refs/tags/` prefix. The result was that the check for the tag matching the package version would always fail.

The workflow is replaced by one that is tried-and-true in many other repositories of the `aiidateam` organization.

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks, could you please remove it from the pre-commit as well?

**Comment by sphuber** [comment]
I noticed that the pre-commit was still relying on the broken script. I think it is better to adopt PEP 621 first and move to building from `pyproject.toml` with `flit` like we do for `aiida-core`. Then we don't need this consistency check. Will open the PR soon

**Comment by ltalirz** [comment]
Thanks - I see you opened a separate PR for the first commit; should that one be merged first?

**Comment by sphuber** [comment]
> Thanks - I see you opened a separate PR for the first commit; should that one be merged first?

Yes, this one is a follow-up

**Comment by ltalirz** [comment]
done!

**Pull request merged**
